#!/bin/sh

if [ "${SKIP_RUNTIME_TESTS:-0}" -eq 1 ]; then
	echo
	echo "======================"
	echo "runtime tests skipped!"
	echo "======================"
	echo
	exit 0
fi

rm -f gmid.pid

. ./lib.sh
. ./tests.sh

trap 'onexit' INT TERM EXIT

if [ $# -ne 0 ]; then
	while [ $# -ne 0 ]; do
		run_test $1
		shift
	done

	tests_done
fi

run_test test_punycode
run_test test_iri
run_test test_configless_mode
run_test test_static_files
run_test test_directory_redirect
run_test test_serve_big_files
run_test test_dont_execute_scripts
run_test test_custom_mime
run_test test_default_type
run_test test_custom_lang
run_test test_parse_custom_lang_per_location
run_test test_cgi_scripts
run_test test_cgi_big_replies
run_test test_cgi_split_query
run_test test_custom_index
run_test test_custom_index_default_type_per_location
run_test test_auto_index
run_test test_block
run_test test_block_return_fmt
run_test test_entrypoint
run_test test_require_client_ca
run_test test_root_inside_location
run_test test_root_inside_location_with_redirect
run_test test_fastcgi
run_test test_macro_expansion
run_test test_174_bugfix

tests_done
