ventura_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
  test_script:
    - make regress

sonoma_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-sonoma-xcode:latest
  test_script:
    - make regress
