# seems that inside the CI it's not currently possible to bind to ::1
# so set HAVE_IPV6=no.

linux_amd64_task:
  container:
    image: alpine:latest
  test_script:
    - apk add alpine-sdk linux-headers bison libretls-dev libevent-dev
    - ./configure CFLAGS='-O2 -pipe -Wno-deprecated-declarations' -Werror
    - make
    - make regress REGRESS_HOST="*" HAVE_IPV6=no

linux_arm_task:
  arm_container:
    image: alpine:latest
  test_script:
    - apk add alpine-sdk linux-headers bison libretls-dev libevent-dev
    - ./configure CFLAGS='-O2 -pipe -Wno-deprecated-declarations' -Werror
    - make
    - make regress REGRESS_HOST="*" HAVE_IPV6=no

freebsd_14_task:
  freebsd_instance:
    image_family: freebsd-14-2
  install_script: pkg install -y libevent libressl pkgconf
  script:
    - ./configure CFLAGS='-O2 -pipe -Wno-deprecated-declarations' -Werror
    - make
    - make regress HAVE_IPV6=no

#
# There are some issues with imsg fd passing on macos at the moment that
# seem to be triggered only in applications that do a heavy use of them,
# like gmid or opensmtpd.  Still, keep macos to ensure gmid builds here.
#
mac_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-sonoma-xcode:latest
  test_script:
    - brew install libevent openssl libretls
    - PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig" ./configure CFLAGS='-O2 -pipe -Wno-deprecated-declarations' -Werror
    - make
    - SKIP_RUNTIME_TESTS=1 make regress
