.\" Copyright (c) 2021 Omar Polo <op@omarpolo.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.Dd $Mdocdate: January 23 2021$
.Dt GG 1
.Os
.Sh NAME
.Nm gg
.Nd simple Gemini client
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl 23bchNVv
.Op Fl H Ar hostname
.Ar IRI
.Ek
.Sh DESCRIPTION
.Nm
is a simple Gemini client.
It fetches the Gemini page given and prints the server response to
standard output.
The option are as follows:
.Bl -tag -width 6m
.It Fl 2
Use only TLSv1.2.
.It Fl 3
Use only TLSv1.3.
.It Fl b
Print only the body of the response.
.It Fl c
Print only the response code.
.It Fl H Ar hostname
Use the given
.Ar hostname
for SNI, instead of the one extracted from the IRI.
The IRI hostname will still be used for the DNS resolution.
.It Fl h
Print only the response header.
.It Fl N
Don't check whether the peer certificate name matches the requested
hostname.
.It Fl V
Only validate the IRI, don't do the Gemini transaction.
.It Fl v
Print also the request.
.El
.Pp
Note that
.Nm
won't try to do TOFU (Trust On First Use) or any X.509 certificate
validation: it will happily accept any certificate it is given.
.Pp
By default
.Nm
will accept both TLSv1.2 and TLSv1.3 and will always do SNI.
